# utils/states.py

# Grant Access Flow
WAITING_EMAIL_GRANT = "WAITING_EMAIL_GRANT"
WAITING_FOLDER_GRANT = "WAITING_FOLDER_GRANT"
WAITING_MULTISELECT_GRANT = "WAITING_MULTISELECT_GRANT"
WAITING_ROLE_GRANT = "WAITING_ROLE_GRANT"
WAITING_DURATION_GRANT = "WAITING_DURATION_GRANT"
WAITING_CONFIRM_GRANT = "WAITING_CONFIRM_GRANT"

# Multi-Email Grant Flow
WAITING_MULTI_EMAIL_INPUT = "WAITING_MULTI_EMAIL_INPUT"
WAITING_MULTI_EMAIL_FOLDER = "WAITING_MULTI_EMAIL_FOLDER"
WAITING_MULTI_EMAIL_ROLE = "WAITING_MULTI_EMAIL_ROLE"
WAITING_MULTI_EMAIL_DURATION = "WAITING_MULTI_EMAIL_DURATION"
WAITING_MULTI_EMAIL_CONFIRM = "WAITING_MULTI_EMAIL_CONFIRM"

# Template Flow
WAITING_TEMPLATE_NAME = "WAITING_TEMPLATE_NAME"
WAITING_TEMPLATE_FOLDERS = "WAITING_TEMPLATE_FOLDERS"
WAITING_TEMPLATE_ROLE = "WAITING_TEMPLATE_ROLE"
WAITING_TEMPLATE_DURATION = "WAITING_TEMPLATE_DURATION"
WAITING_APPLY_EMAIL = "WAITING_APPLY_EMAIL"
WAITING_APPLY_CONFIRM = "WAITING_APPLY_CONFIRM"

# Manage Folder Flow
WAITING_FOLDER_MANAGE = "WAITING_FOLDER_MANAGE"
WAITING_USER_MANAGE = "WAITING_USER_MANAGE"
WAITING_ACTION_MANAGE = "WAITING_ACTION_MANAGE"

# Settings Flow
WAITING_DEFAULT_ROLE = "WAITING_DEFAULT_ROLE"
WAITING_PAGE_SIZE = "WAITING_PAGE_SIZE"
WAITING_CHANNEL_ID = "WAITING_CHANNEL_ID"
WAITING_SEARCH_QUERY = "WAITING_SEARCH_QUERY"
WAITING_CONFIRM_REVOKE_ALL = "WAITING_CONFIRM_REVOKE_ALL"

# Manage Folder - Revoke All
CONFIRM_FOLDER_REVOKE_ALL = "CONFIRM_FOLDER_REVOKE_ALL"

# Template Apply - Duration Override
WAITING_APPLY_DURATION_OVERRIDE = "WAITING_APPLY_DURATION_OVERRIDE"
