# utils/states.py

# Grant Access Flow
WAITING_EMAIL_GRANT = "WAITING_EMAIL_GRANT"
WAITING_FOLDER_GRANT = "WAITING_FOLDER_GRANT"
WAITING_ROLE_GRANT = "WAITING_ROLE_GRANT"
WAITING_DURATION_GRANT = "WAITING_DURATION_GRANT"
WAITING_CONFIRM_GRANT = "WAITING_CONFIRM_GRANT"

# Manage Folder Flow
WAITING_FOLDER_MANAGE = "WAITING_FOLDER_MANAGE"
WAITING_USER_MANAGE = "WAITING_USER_MANAGE"
WAITING_ACTION_MANAGE = "WAITING_ACTION_MANAGE"

# Settings Flow
WAITING_DEFAULT_ROLE = "WAITING_DEFAULT_ROLE"
WAITING_PAGE_SIZE = "WAITING_PAGE_SIZE"
